version: '3.9'

services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: local-keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: local-keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: local-keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloakgi
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
  local-keycloak: